CC     = gcc
OBJS   = main.o
# -W* for warnings, -g3 for maximum debug, -O3 for maximum optimization
CFLAGS = -Wall -Wextra -Wundef -Wshadow -Wwrite-strings -Wcast-align -Wstrict-prototypes -Waggregate-return \
         -Wcast-qual -Wswitch-default -Wswitch-enum -Wconversion -Wunreachable-code -Wfloat-equal -g3 -O3  #-Wpointer-arith 

all: main

main: $(OBJS) alloc.o
	$(CC) $(CFLAGS) -o $@ $^

run: main
	./main

# deletes files generated by compilation
clean:
	rm -f *.o main memory.so

main.o: main.c alloc.o
alloc.o: alloc.c alloc.h

